version: '3.1'

services:
  crm_service:
      container_name: crm_mevada
      build: .
      ports:
        - 5001:5001
      networks:
      - crm_network
  crm_mongo:
    container_name: mongo_crm
    image: mongo:4.4.18-focal
    ports:
      - 127.0.0.1:27019:27017
    networks:
      - crm_network
    volumes:
      - /home/sena/docker/data/mongodb:/data/db

networks:
  crm_network:
    external: true